version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=petadmin
      - DB_PASS=petpassword
      - DB_NAME=pet_adoption

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pet_adoption
      MYSQL_USER: petadmin
      MYSQL_PASSWORD: petpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/pet_adoption.sql:/docker-entrypoint-initdb.d/pet_adoption.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  mysql_data:
